### ISSUE TITLE
Update Hedera version

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/hedera-solo-action#4]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to hedera-enterprise or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/OpenElements/hedera-enterprise/labels/good%20first%20issue) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

Today version `0.51.5` of Hedera is used. That can be seen in the following line of the action:

```
solo init -i node0 -t v0.51.5 -n solo-test --key-format pem --profile local
```

When creating this issue Hedere Mainnet is already updated to version `v0.52.2`. The current version of Hedera Mainnet can be found at https://status.hedera.com

The Action should be updated in a way that the version becomes an inout parameter for the script. This input parameter should be optional and the default value should be the version of Mainnet at that moment. By doing so projects can easily change a version if they want to run against a specific verison (like the one installed on testnet).

### Suggested solution

Create an optional `hederaVersion` input paremeter with a default value equals to the current version of Mainnet. That version must be used in the script. The script already contains the input parameter `installMirrorNode` that can be used as an example of how input parameters work.

Additional information about inputs in GitHub actions can be found here: https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#inputs

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in the hedera-enterprise repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional informantion

If you have any questions, just ask us directly in this issue by adding a comment. You can join the Hedera community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by Firdous2307** [comment]
Hi, I would like to work on this issue regarding Hedera Version, please let me know how I can assist

**Comment by Atharva1723** [comment]
Can I work on this issue?
